export const REQUEST_STATS = 'REQUEST_STATS'
export const REQUEST_STATS_ERROR = 'REQUEST_STATS_ERROR'
export const RECEIVE_STATS = 'RECEIVE_STATS'
export const REQUEST_SAVE_SHRINE_COMPLETION = 'REQUEST_SAVE_SHRINE_COMPLETION'
export const REQUEST_SAVE_SHRINE_QUEST_COMPLETION =
  'REQUEST_SAVE_SHRINE_QUEST_COMPLETION'
